version: '2'
services:
  app:
    image: userauthentication_ms
    container_name: userauthentication_ms
    build: ./
    restart: always
    ports:
      - "8085:3000"
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: userauthentication
      MYSQL_PASSWORD: secret
      MYSQL_DB: userauthentication_db

  db:
    image: mysql:5.7
    container_name: userauthentication_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userauthentication_db
      MYSQL_USER: userauthentication
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - ./userauthentication.sql:/docker-entrypoint-initdb.d/userauthentication.sql
      - dbdata:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8089:80
volumes:
  dbdata:
